version: "2"
services:
 rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
 app:
    build: ./generate_service
    container_name: thaiFood
    restart: always
    depends_on:
      - rabbitmq
    ports:
      - "4000:4000"
    links:
      - mongo
 mongo:
    container_name: thaiFooddb
    image: mongo
   
    ports:
      - "27017:27017"