version: "2"
services:
  app:
    build: ./server 
    container_name: thaiFood
    restart: always
    ports:
      - "4000:4000"
    links:
      - mongo
  mongo:
    container_name: thaiFooddb
    image: mongo
   
    ports:
      - "27017:27017"