version: '3.8'
services:
    nginx:
        image: phongsakorn/nginx:latest
        restart: always
        depends_on:
            - fastapi
            - express
        ports:
            - "80:80"

    fastapi:
      container_name: fastapi
      image: phongsakorn/fastapi:latest
     

   

    express:
      container_name: express
      image: phongsakorn/express:latest
     
    
     